In [ ]:
# Restaurant Sales Data Analysis
# Author: Your Name
# Date: October 2025

# --- Import Libraries ---
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

# --- Load Data ---
data = pd.read_csv("restaurant_sales_data.csv")
data.head()

,InvoiceID,Date,CustomerID,Gender,AgeGroup,Region,ProductCategory,ProductName,Quantity,UnitPrice,TotalSale,Discount,Profit,PaymentMethod
0,INV000001,2023-01-01,CUST6734,Male,36-45,Durban,Drinks,Wine,4,238.66,954.64,69.88,362.38,Cash
1,INV000002,2023-01-01,CUST9322,Female,46-60,Cape Town,Starters,Chicken Wings,2,55.88,111.76,0.65,51.39,EFT
2,INV000003,2023-01-01,CUST3433,Female,60+,Johannesburg,Desserts,Pudding,2,32.97,65.94,4.76,31.75,EFT
3,INV000004,2023-01-01,CUST7396,Male,26-35,Durban,Main Course,Grilled Chicken,4,248.21,992.84,61.31,380.75,Card
4,INV000005,2023-01-01,CUST3047,Female,46-60,Johannesburg,Starters,Soup of the Day,4,25.30,101.20,5.31,32.38,Cash

In [3]:
# --- Basic Info ---
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51042 entries, 0 to 51041
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   InvoiceID        51042 non-null  object
 1   Date             51042 non-null  object
 2   CustomerID       51042 non-null  object
 3   Gender           51042 non-null  object
 4   AgeGroup         51042 non-null  object
 5   Region           51042 non-null  object
 6   ProductCategory  51042 non-null  object
 7   ProductName      51042 non-null  object
 8   Quantity         51042 non-null  int64
 9   UnitPrice        51042 non-null  float64
 10  TotalSale        51042 non-null  float64
 11  Discount         51042 non-null  float64
 12  Profit           51042 non-null  float64
 13  PaymentMethod    51042 non-null  object
dtypes: float64(4), int64(1), object(9)
memory usage: 5.5+ MB

           Quantity     UnitPrice     TotalSale      Discount        Profit
count  51042.000000  51042.000000  51042.000000  51042.000000  51042.000000
mean       2.498883    135.214556    338.104055     16.903116    118.393014
std        1.116449     66.392492    236.497967     16.782107     90.132476
min        1.000000     20.010000     20.010000      0.000000      4.150000
25%        1.000000     77.660000    148.950000      4.670000     48.760000
50%        3.000000    135.620000    269.740000     11.240000     92.610000
75%        3.000000    192.657500    482.305000     23.580000    167.640000
max        4.000000    249.990000    999.880000     98.890000    496.510000